config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "customers#index"

  get "/customers/alphabetized", to: "customers#alphabetized"
  get "/customers/missing_email", to: "customers#missing_email"


  # resources :customers, only: [:index]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email_address", "full_name", "id", "notes", "phone_number", "updated_at"]
  end

  validates :full_name, presence: true
  validates :phone_number, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email_address: [nil, ""])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div>
  <h2><%= customer.full_name%></h2>
  <p>phone number:<%= customer.phone_number %></p>
  <% if customer.email_address.present? %>
    <p>email:<%= customer.email_address %></p>
  <% end %>
  <% if customer.notes.present? %>
    <p>Notes:<%= customer.notes %></p>
  <% end %>
  <%# todo add img %>
</div>

app/views/customers/alphabetized.html.erb
<h1>Customers in alphabetical order</h1>

<nav>
  <%= link_to "all customers", root_path %> |
  <%= link_to "missing email", customers_missing_email_path %>
</nav>

<% @customers.each do |customer| %>
  <%= render partial: "customer", locals: { customer: customer } %>
<% end %>

app/views/customers/index.html.erb
<h1>Customers</h1>

<nav>
  <%= link_to "alphabetized", customers_alphabetized_path %> |
  <%= link_to "missing email", customers_missing_email_path %>
</nav>

<% @customers.each do |customer| %>
  <%= render partial: "customer", locals: { customer: customer }%>
<% end %>

app/views/customers/missing_email.html.erb
<h1>Customers missing an email address</h1>

<nav>
  <%= link_to "all customers", root_path %> |
  <%= link_to "alphabetized", customers_alphabetized_path %>
</nav>


<% @customers.each do |customer| %>
  <%= render partial: "customer", locals: { customer: customer } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>